/**
 * Provincias de Peru por codigo de departamento, sincronizadas desde el BO
 * personalizado de C4C produccion (cust/v1/provincias/BOProvinciasRootCollection)
 * - misma fuente que usa C4C para la pantalla "Provincias" de Gestion de datos
 * personalizados. id = zIDProvincia (el valor que espera direccion.provincia).
 */
export interface Provincia {
  id: string;
  nombre: string;
  departamentoId: string;
}

export const PERU_PROVINCIAS: Provincia[] = [
  { id: "2", nombre: "BAGUA", departamentoId: "01" },
  { id: "3", nombre: "BONGARA", departamentoId: "01" },
  { id: "1", nombre: "CHACHAPOYAS", departamentoId: "01" },
  { id: "4", nombre: "CONDORCANQUI", departamentoId: "01" },
  { id: "5", nombre: "LUYA", departamentoId: "01" },
  { id: "6", nombre: "RODRIGUEZ DE MENDOZA", departamentoId: "01" },
  { id: "7", nombre: "UTCUBAMBA", departamentoId: "01" },
  { id: "9", nombre: "AIJA", departamentoId: "02" },
  { id: "10", nombre: "ANTONIO RAYMONDI", departamentoId: "02" },
  { id: "11", nombre: "ASUNCION", departamentoId: "02" },
  { id: "12", nombre: "BOLOGNESI", departamentoId: "02" },
  { id: "13", nombre: "CARHUAZ", departamentoId: "02" },
  { id: "14", nombre: "CARLOS F.FITZCARRALD", departamentoId: "02" },
  { id: "15", nombre: "CASMA", departamentoId: "02" },
  { id: "16", nombre: "CORONGO", departamentoId: "02" },
  { id: "8", nombre: "HUARAZ", departamentoId: "02" },
  { id: "17", nombre: "HUARI", departamentoId: "02" },
  { id: "18", nombre: "HUARMEY", departamentoId: "02" },
  { id: "19", nombre: "HUAYLAS", departamentoId: "02" },
  { id: "20", nombre: "MARISCAL LUZURIAGA", departamentoId: "02" },
  { id: "21", nombre: "OCROS", departamentoId: "02" },
  { id: "22", nombre: "PALLASCA", departamentoId: "02" },
  { id: "23", nombre: "POMABAMBA", departamentoId: "02" },
  { id: "24", nombre: "RECUAY", departamentoId: "02" },
  { id: "25", nombre: "SANTA", departamentoId: "02" },
  { id: "26", nombre: "SIHUAS", departamentoId: "02" },
  { id: "27", nombre: "YUNGAY", departamentoId: "02" },
  { id: "28", nombre: "ABANCAY", departamentoId: "03" },
  { id: "29", nombre: "ANDAHUAYLAS", departamentoId: "03" },
  { id: "30", nombre: "ANTABAMBA", departamentoId: "03" },
  { id: "31", nombre: "AYMARAES", departamentoId: "03" },
  { id: "33", nombre: "CHINCHEROS", departamentoId: "03" },
  { id: "32", nombre: "COTABAMBAS", departamentoId: "03" },
  { id: "34", nombre: "GRAU", departamentoId: "03" },
  { id: "35", nombre: "AREQUIPA", departamentoId: "04" },
  { id: "36", nombre: "CAMANA", departamentoId: "04" },
  { id: "37", nombre: "CARAVELI", departamentoId: "04" },
  { id: "38", nombre: "CASTILLA", departamentoId: "04" },
  { id: "39", nombre: "CAYLLOMA", departamentoId: "04" },
  { id: "40", nombre: "CONDESUYOS", departamentoId: "04" },
  { id: "41", nombre: "ISLAY", departamentoId: "04" },
  { id: "42", nombre: "LA UNION", departamentoId: "04" },
  { id: "44", nombre: "CANGALLO", departamentoId: "05" },
  { id: "43", nombre: "HUAMANGA", departamentoId: "05" },
  { id: "45", nombre: "HUANCA SANCOS", departamentoId: "05" },
  { id: "46", nombre: "HUANTA", departamentoId: "05" },
  { id: "47", nombre: "LA MAR", departamentoId: "05" },
  { id: "48", nombre: "LUCANAS", departamentoId: "05" },
  { id: "49", nombre: "PARINACOCHAS", departamentoId: "05" },
  { id: "50", nombre: "PAUCAR DEL SARA SARA", departamentoId: "05" },
  { id: "51", nombre: "SUCRE", departamentoId: "05" },
  { id: "52", nombre: "VICTOR FAJARDO", departamentoId: "05" },
  { id: "53", nombre: "VILCAS HUAMAN", departamentoId: "05" },
  { id: "55", nombre: "CAJABAMBA", departamentoId: "06" },
  { id: "54", nombre: "CAJAMARCA", departamentoId: "06" },
  { id: "56", nombre: "CELENDIN", departamentoId: "06" },
  { id: "57", nombre: "CHOTA", departamentoId: "06" },
  { id: "58", nombre: "CONTUMAZA", departamentoId: "06" },
  { id: "59", nombre: "CUTERVO", departamentoId: "06" },
  { id: "60", nombre: "HUALGAYOC", departamentoId: "06" },
  { id: "61", nombre: "JAEN", departamentoId: "06" },
  { id: "62", nombre: "SAN IGNACIO", departamentoId: "06" },
  { id: "63", nombre: "SAN MARCOS", departamentoId: "06" },
  { id: "64", nombre: "SAN MIGUEL", departamentoId: "06" },
  { id: "65", nombre: "SAN PABLO", departamentoId: "06" },
  { id: "66", nombre: "SANTA CRUZ", departamentoId: "06" },
  { id: "67", nombre: "CALLAO", departamentoId: "07" },
  { id: "69", nombre: "ACOMAYO", departamentoId: "08" },
  { id: "70", nombre: "ANTA", departamentoId: "08" },
  { id: "71", nombre: "CALCA", departamentoId: "08" },
  { id: "72", nombre: "CANAS", departamentoId: "08" },
  { id: "73", nombre: "CANCHIS", departamentoId: "08" },
  { id: "74", nombre: "CHUMBIVILCAS", departamentoId: "08" },
  { id: "68", nombre: "CUSCO", departamentoId: "08" },
  { id: "75", nombre: "ESPINAR", departamentoId: "08" },
  { id: "76", nombre: "LA CONVENCION", departamentoId: "08" },
  { id: "77", nombre: "PARURO", departamentoId: "08" },
  { id: "78", nombre: "PAUCARTAMBO", departamentoId: "08" },
  { id: "79", nombre: "QUISPICANCHI", departamentoId: "08" },
  { id: "80", nombre: "URUBAMBA", departamentoId: "08" },
  { id: "82", nombre: "ACOBAMBA", departamentoId: "09" },
  { id: "83", nombre: "ANGARAES", departamentoId: "09" },
  { id: "84", nombre: "CASTROVIRREYNA", departamentoId: "09" },
  { id: "85", nombre: "CHURCAMPA", departamentoId: "09" },
  { id: "81", nombre: "HUANCAVELICA", departamentoId: "09" },
  { id: "86", nombre: "HUAYTARA", departamentoId: "09" },
  { id: "87", nombre: "TAYACAJA", departamentoId: "09" },
  { id: "89", nombre: "AMBO", departamentoId: "10" },
  { id: "90", nombre: "DOS DE MAYO", departamentoId: "10" },
  { id: "91", nombre: "HUACAYBAMBA", departamentoId: "10" },
  { id: "92", nombre: "HUAMALIES", departamentoId: "10" },
  { id: "88", nombre: "HUANUCO", departamentoId: "10" },
  { id: "97", nombre: "LAURICOCHA", departamentoId: "10" },
  { id: "93", nombre: "LEONCIO PRADO", departamentoId: "10" },
  { id: "94", nombre: "MARAÑON", departamentoId: "10" },
  { id: "95", nombre: "PACHITEA", departamentoId: "10" },
  { id: "96", nombre: "PUERTO INCA", departamentoId: "10" },
  { id: "98", nombre: "YAROWILCA", departamentoId: "10" },
  { id: "100", nombre: "CHINCHA", departamentoId: "11" },
  { id: "99", nombre: "ICA", departamentoId: "11" },
  { id: "101", nombre: "NAZCA", departamentoId: "11" },
  { id: "102", nombre: "PALPA", departamentoId: "11" },
  { id: "103", nombre: "PISCO", departamentoId: "11" },
  { id: "105", nombre: "CHANCHAMAYO", departamentoId: "12" },
  { id: "111", nombre: "CHUPACA", departamentoId: "12" },
  { id: "114", nombre: "CONCEPCION", departamentoId: "12" },
  { id: "104", nombre: "HUANCAYO", departamentoId: "12" },
  { id: "106", nombre: "JAUJA", departamentoId: "12" },
  { id: "107", nombre: "JUNIN", departamentoId: "12" },
  { id: "108", nombre: "SATIPO", departamentoId: "12" },
  { id: "109", nombre: "TARMA", departamentoId: "12" },
  { id: "110", nombre: "YAULI", departamentoId: "12" },
  { id: "113", nombre: "ASCOPE", departamentoId: "13" },
  { id: "115", nombre: "BOLIVAR", departamentoId: "13" },
  { id: "116", nombre: "CHEPEN", departamentoId: "13" },
  { id: "123", nombre: "GRAN CHIMU", departamentoId: "13" },
  { id: "117", nombre: "JULCAN", departamentoId: "13" },
  { id: "118", nombre: "OTUZCO", departamentoId: "13" },
  { id: "119", nombre: "PACASMAYO", departamentoId: "13" },
  { id: "120", nombre: "PATAZ", departamentoId: "13" },
  { id: "121", nombre: "SANCHEZ CARRION", departamentoId: "13" },
  { id: "122", nombre: "SANTIAGO DE CHUCO", departamentoId: "13" },
  { id: "112", nombre: "TRUJILLO", departamentoId: "13" },
  { id: "124", nombre: "VIRU", departamentoId: "13" },
  { id: "125", nombre: "CHICLAYO", departamentoId: "14" },
  { id: "126", nombre: "FERREÑAFE", departamentoId: "14" },
  { id: "127", nombre: "LAMBAYEQUE", departamentoId: "14" },
  { id: "129", nombre: "BARRANCA", departamentoId: "15" },
  { id: "130", nombre: "CAJATAMBO", departamentoId: "15" },
  { id: "131", nombre: "CANTA", departamentoId: "15" },
  { id: "132", nombre: "CAÑETE", departamentoId: "15" },
  { id: "133", nombre: "HUARAL", departamentoId: "15" },
  { id: "134", nombre: "HUAROCHIRI", departamentoId: "15" },
  { id: "135", nombre: "HUAURA", departamentoId: "15" },
  { id: "128", nombre: "LIMA", departamentoId: "15" },
  { id: "136", nombre: "OYON", departamentoId: "15" },
  { id: "137", nombre: "YAUYOS", departamentoId: "15" },
  { id: "183", nombre: "ALTO AMAZONAS", departamentoId: "16" },
  { id: "139", nombre: "LORETO", departamentoId: "16" },
  { id: "140", nombre: "MARISCAL RAMON CASTILLA", departamentoId: "16" },
  { id: "138", nombre: "MAYNAS", departamentoId: "16" },
  { id: "141", nombre: "REQUENA", departamentoId: "16" },
  { id: "142", nombre: "UCAYALI", departamentoId: "16" },
  { id: "144", nombre: "MANU", departamentoId: "17" },
  { id: "145", nombre: "TAHUAMANU", departamentoId: "17" },
  { id: "143", nombre: "TAMBOPATA", departamentoId: "17" },
  { id: "147", nombre: "GRAL.SANCHEZ CERRO", departamentoId: "18" },
  { id: "148", nombre: "ILO", departamentoId: "18" },
  { id: "146", nombre: "MARISCAL NIETO", departamentoId: "18" },
  { id: "150", nombre: "DANIEL ALCIDES CARRION", departamentoId: "19" },
  { id: "151", nombre: "OXAPAMPA", departamentoId: "19" },
  { id: "149", nombre: "PASCO", departamentoId: "19" },
  { id: "153", nombre: "AYABACA", departamentoId: "20" },
  { id: "154", nombre: "HUANCABAMBA", departamentoId: "20" },
  { id: "155", nombre: "MORROPON", departamentoId: "20" },
  { id: "156", nombre: "PAITA", departamentoId: "20" },
  { id: "152", nombre: "PIURA", departamentoId: "20" },
  { id: "159", nombre: "SECHURA", departamentoId: "20" },
  { id: "157", nombre: "SULLANA", departamentoId: "20" },
  { id: "158", nombre: "TALARA", departamentoId: "20" },
  { id: "161", nombre: "AZANGARO", departamentoId: "21" },
  { id: "162", nombre: "CARABAYA", departamentoId: "21" },
  { id: "163", nombre: "CHUCUITO", departamentoId: "21" },
  { id: "164", nombre: "EL COLLAO", departamentoId: "21" },
  { id: "165", nombre: "HUANCANE", departamentoId: "21" },
  { id: "166", nombre: "LAMPA", departamentoId: "21" },
  { id: "167", nombre: "MELGAR", departamentoId: "21" },
  { id: "168", nombre: "MOHO", departamentoId: "21" },
  { id: "160", nombre: "PUNO", departamentoId: "21" },
  { id: "169", nombre: "SAN ANTONIO DE PUTINA", departamentoId: "21" },
  { id: "170", nombre: "SAN ROMAN", departamentoId: "21" },
  { id: "171", nombre: "SANDIA", departamentoId: "21" },
  { id: "172", nombre: "YUNGUYO", departamentoId: "21" },
  { id: "174", nombre: "BELLAVISTA", departamentoId: "22" },
  { id: "175", nombre: "EL DORADO", departamentoId: "22" },
  { id: "176", nombre: "HUALLAGA", departamentoId: "22" },
  { id: "177", nombre: "LAMAS", departamentoId: "22" },
  { id: "178", nombre: "MARISCAL CACERES", departamentoId: "22" },
  { id: "173", nombre: "MOYOBAMBA", departamentoId: "22" },
  { id: "179", nombre: "PICOTA", departamentoId: "22" },
  { id: "180", nombre: "RIOJA", departamentoId: "22" },
  { id: "181", nombre: "SAN MARTIN", departamentoId: "22" },
  { id: "182", nombre: "TOCACHE", departamentoId: "22" },
  { id: "185", nombre: "CANDARAVE", departamentoId: "23" },
  { id: "186", nombre: "JORGE BASADRE", departamentoId: "23" },
  { id: "184", nombre: "TACNA", departamentoId: "23" },
  { id: "187", nombre: "TARATA", departamentoId: "23" },
  { id: "189", nombre: "CONTRALMIRANTE VILLAR", departamentoId: "24" },
  { id: "188", nombre: "TUMBES", departamentoId: "24" },
  { id: "190", nombre: "ZARUMILLA", departamentoId: "24" },
  { id: "192", nombre: "ATALAYA", departamentoId: "25" },
  { id: "191", nombre: "CORONEL PORTILLO", departamentoId: "25" },
  { id: "193", nombre: "PADRE ABAD", departamentoId: "25" },
  { id: "194", nombre: "PURUS", departamentoId: "25" },
];
